<?php

/**
 * @file
 * Contains tui_editor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function tui_editor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the editor_md module.
    case 'help.page.tui_editor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Toast UI Editor integration - GFM Markdown WYSIWYG Editor.') . '</p>';
      return $output;

    default:
  }
}
